name: laba Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Display GitHub User Info
      run: |
        echo "Бастрыгин Тимофей Сергеевич"
        echo "M3112"
        echo "timabast"
    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest tests/
    - name: Check code style
      run: |
        pip install flake8
        flake8 . tests
